# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import libentry
from flag_gems.utils.triton_lang_extension import program_id

logger = logging.getLogger(__name__)


@libentry()
@triton.jit
def cholesky_kernel(A, L, N, batch_stride, stride_a, stride_l):
    """Cholesky decomposition kernel.

    Each program computes one matrix in the batch.
    """
    pid = program_id(0)

    # Each matrix is N*N elements; batch_stride is the stride between matrices
    a_offset = pid * batch_stride
    l_offset = pid * batch_stride

    # Sequential Cholesky: L[i,j] for j <= i
    for i in range(N):
        for j in range(i + 1):
            # Accumulate in the input dtype to support float32 and float64
            sum_val = tl.zeros((), dtype=A.dtype.element_ty)

            # sum(L[i,k] * L[j,k]) for k in [0, j)
            if j > 0:
                for k in range(j):
                    sum_val = sum_val + tl.load(
                        L + l_offset + i * stride_l + k
                    ) * tl.load(L + l_offset + j * stride_l + k)

            if j == i:
                # Diagonal: L[i,i] = sqrt(A[i,i] - sum)
                a_diag = tl.load(A + a_offset + i * stride_a + i)
                result = tl.sqrt(a_diag - sum_val)
                tl.store(L + l_offset + i * stride_l + i, result)
            else:
                # Off-diagonal: L[i,j] = (A[i,j] - sum) / L[j,j]
                a_val = tl.load(A + a_offset + i * stride_a + j)
                l_diag = tl.load(L + l_offset + j * stride_l + j)
                result = (a_val - sum_val) / l_diag
                tl.store(L + l_offset + i * stride_l + j, result)


def linalg_cholesky(A, upper=False):
    logger.debug("GEMS LINALG_CHOLESKY")
    assert A.dtype in (
        torch.float32,
        torch.float64,
    ), "linalg_cholesky only supports float32 and float64"

    if A.numel() == 0:
        return A

    shape = A.shape
    if len(shape) < 2:
        raise ValueError("A must be at least 2D")

    n = shape[-1]
    m = shape[-2]

    if m != n:
        raise ValueError("A must be a square matrix")

    # Handle batch dimensions
    if len(shape) == 2:
        batch_size = 1
    else:
        batch_dims = shape[:-2]
        batch_size = 1
        for dim in batch_dims:
            batch_size *= dim

    # Create output tensor - use contiguous format
    L = torch.empty_like(A)

    # Ensure A is symmetric positive definite
    # Symmetrize: A = (A + A^T) / 2
    if len(shape) == 2:
        A_sym = (A + A.t().conj()) / 2
    else:
        # For batched, reshape to (batch, n, n) then symmetrize
        A_view = A.reshape(-1, n, n)
        A_sym_view = (A_view + A_view.transpose(1, 2).conj()) / 2
        A_sym = A_sym_view.reshape(shape)

    # Add small identity to ensure positive definiteness
    eps = 1e-5
    if len(shape) == 2:
        A_sym = A_sym + torch.eye(n, dtype=A.dtype, device=A.device) * eps
    else:
        eye = torch.eye(n, dtype=A.dtype, device=A.device)
        for _ in range(len(shape) - 2):
            eye = eye.unsqueeze(0)
        A_sym = A_sym + eye.expand(shape[:-2] + (n, n)) * eps

    # For kernel: use contiguous 2D view
    if len(shape) > 2:
        A_kernel = A_sym.reshape(-1, n, n)
        L_kernel = L.reshape(-1, n, n)
        stride_a = A_kernel.stride(1)  # row stride within a matrix = n
        stride_l = L_kernel.stride(1)
        batch_stride = A_kernel.stride(0)  # stride between matrices = n * n
    else:
        A_kernel = A_sym
        L_kernel = L
        stride_a = A_sym.stride(0)
        stride_l = L.stride(0)
        batch_stride = stride_a * n  # n * n; pid=0 so a_offset = 0

    grid = (batch_size,)

    with torch.no_grad():
        cholesky_kernel[grid](
            A_kernel,
            L_kernel,
            n,
            batch_stride,
            stride_a,
            stride_l,
        )

    # Zero upper triangle
    if len(shape) > 2:
        L = L.reshape(-1, n, n)
        L = torch.tril(L)
        L = L.reshape(shape)
    else:
        L = torch.tril(L)

    if upper:
        L = L.transpose(-2, -1).conj()

    return L
