from kernels.contraction.gemm import Activation


# Representative author specializations for the compile-only shared GPU
# inventory.  Discovery is performed independently over every @intent.kernel;
# this mapping only supplies values for signatures that deliberately require
# compile-time arguments.
SHARED_COMPILE_BINDINGS: dict[str, dict[str, object]] = {
    "kernels.backward.attention:attention_backward_dkdv": {"HEAD_GROUP": 8, "CAUSAL": True},
    "kernels.backward.attention:attention_backward_dq": {"HEAD_GROUP": 8, "CAUSAL": True},
    "kernels.backward.sparse_mla:sparse_mla_backward_main": {"HEAD_GROUP": 8},
    "kernels.contraction.gemm:gemm": {"ACTIVATION": Activation.NONE},
    "kernels.convolution.direct:causal_depthwise_conv1d": {"SILU": True},
    "kernels.convolution.direct:causal_depthwise_conv1d_bf16": {"SILU": True},
    "kernels.convolution.direct:causal_depthwise_conv1d_update": {"SILU": True},
    "kernels.convolution.direct:causal_depthwise_conv1d_update_bf16": {"SILU": True},
    "kernels.indexing.relations:roll_rows_forward": {"ROW_WIDTH": 4096},
    "kernels.loss.cross_entropy:fused_cross_entropy": {"IGNORE_INDEX": -100},
    "kernels.loss.cross_entropy:fused_cross_entropy_bf16": {"IGNORE_INDEX": -100},
    "kernels.loss.cross_entropy:flash_cross_entropy_bf16": {"IGNORE_INDEX": -100, "Z_LOSS_SCALE": 0.0},
    "kernels.position.rope:rotary_embedding_flat": {"HEADS": 32},
    "kernels.ragged.grouped_gemm:routed_expert_projection_bf16": {"TOP_K": 2},
    "kernels.routing.mhc:mhc_gemm_rms_scale": {"STREAMS": 4, "ALPHA_PRE": 1.0, "ALPHA_POST": 1.0, "ALPHA_RESIDUAL": 1.0},
    "kernels.routing.mhc:mhc_pre_fuse": {"RMS_EPS": 1.0e-6, "PRE_EPS": 1.0e-6, "SINKHORN_EPS": 1.0e-6, "POST_MULTIPLIER": 1.0, "SINKHORN_REPEATS": 2},
    "kernels.streaming.attention:flash_attention_fwd": {"CAUSAL": True},
    "kernels.streaming.attention:flash_gqa_attention_fwd": {"HEAD_GROUP": 8, "CAUSAL": True},
    "kernels.streaming.attention:flash_attention_bf16_fwd": {"HEAD_GROUP": 8, "CAUSAL": True},
    "kernels.streaming.attention:grouped_flash_decode_partials": {"HEAD_GROUP": 8, "P": 4, "SPLIT_SIZE": 256},
    "kernels.streaming.attention:continuous_gqa_decode": {"HEAD_GROUP": 8},
    "kernels.streaming.attention:varlen_gqa_decode_with_sink_logits": {"HEAD_GROUP": 8, "MAX_BLOCKS": 64},
    "kernels.streaming.attention:mla_prefill": {"HEAD_GROUP": 8},
    "kernels.streaming.attention:flash_varlen_attention_fwd": {"CAUSAL": True},
    "kernels.streaming.attention:flash_varlen_gqa_prefill": {"HEAD_GROUP": 8},
    "kernels.streaming.attention_specialized:attention_sink_prefill": {"HEAD_GROUP": 8},
    "kernels.streaming.attention_specialized:attention_sink_decode_partials": {"HEAD_GROUP": 8, "WINDOW": 4096, "P": 4},
    "kernels.streaming.attention_specialized:gemma_gqa_prefill": {"HEAD_GROUP": 8, "WINDOW": 4096, "SOFT_CAP": 50.0},
    "kernels.streaming.attention_specialized:gemma_gqa_decode_partials": {"HEAD_GROUP": 8, "WINDOW": 4096, "SOFT_CAP": 50.0, "P": 4},
    "kernels.streaming.attention_specialized:sliding_window_gqa_prefill": {"HEAD_GROUP": 8, "WINDOW": 4096},
    "kernels.streaming.attention_specialized:block_causal_attention_fwd": {"BLOCK": 128},
    "kernels.streaming.attention_specialized:native_sparse_attention_fwd": {"HEAD_GROUP": 8, "BLOCK": 128},
    "kernels.streaming.attention_specialized:varlen_block_causal_attention_fwd": {"BLOCK": 128},
    "kernels.streaming.block_sparse_attention:block_sparse_gqa_decode_partials": {"HEAD_GROUP": 8, "BLOCK_SIZE": 128, "SPLITS": 4},
    "kernels.streaming.block_sparse_attention:block_sparse_gqa_decode_combine": {"SPLITS": 4},
    "kernels.streaming.gated_delta:recurrent_gated_delta_fwd": {"HEAD_GROUP": 8},
    "kernels.streaming.mamba:mamba_chunk_state_fwd": {"HEAD_GROUP": 8},
    "kernels.streaming.mamba:mamba_chunk_state_bf16_fwd": {"HEAD_GROUP": 8},
    "kernels.streaming.mamba:mamba3_siso_step": {"HEAD_GROUP": 8},
    "kernels.streaming.mamba:mamba3_siso_forward": {"HEAD_GROUP": 8},
    "kernels.streaming.mla:paged_mla_decode": {"PAGE_SIZE": 64, "HEAD_GROUP": 8},
    "kernels.streaming.mla:paged_mla_decode_partials": {"PAGE_SIZE": 64, "HEAD_GROUP": 8, "SPLITS": 4},
    "kernels.streaming.mla:splitk_mla_decode_partials": {"SPLITS": 4},
    "kernels.streaming.paged_attention:paged_gqa_decode_attention": {"PAGE_SIZE": 64, "HEAD_GROUP": 8},
    "kernels.streaming.paged_attention:paged_gqa_decode_partials": {"PAGE_SIZE": 64, "HEAD_GROUP": 8, "SPLITS": 4},
    "kernels.streaming.paged_attention:splitk_paged_gqa_decode_partials": {"PAGE_SIZE": 64, "HEAD_GROUP": 8, "SPLITS": 4},
    "kernels.streaming.selective_scan:mamba_chunk_scan_fwd": {"HEADS_PER_GROUP": 8},
    "kernels.streaming.selective_scan:mamba_chunk_scan_bf16_fwd": {"HEADS_PER_GROUP": 8},
    "kernels.variants.contraction:gemm_loop_interchange": {"ACTIVATION": Activation.NONE},
    "kernels.variants.indexing:rotary_embedding_equivalent_index": {"HEADS": 32},
    "kernels.variants.streaming:flash_attention_inline_fwd": {"CAUSAL": True},
    "kernels.variants.streaming:flash_attention_select_fwd": {"CAUSAL": True},
    "kernels.variants.streaming:flash_attention_full_causal_stream_fwd": {"CAUSAL": True},
}
