from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Entry:
    kernel: str
    case: str
    generated: str
    examples: tuple[str, ...]
    source_runtime: str
    deployment: str | None = None


TRITON = (
    Entry("fused_softmax", "8192x8192-fp16", "softmax_f16", ("normalization/softmax.py:stable_softmax_f16",), "source/triton/triton/normalization/softmax/02-fused-softmax_runtime.py"),
    Entry("dense_gemm", "M4096-N14336-K4096-fp16", "dense_gemm", ("contraction/gemm.py:gemm",), "source/triton/triton/gemm/dense/03-matrix-multiplication_runtime.py"),
    Entry("grouped_gemm", "E8-M1024-K4096-N14336-fp16", "grouped_gemm_v2", ("ragged/grouped_gemm.py:ragged_grouped_gemm",), "source/triton/triton/gemm/grouped/08-grouped-gemm_runtime.py"),
    Entry("flash_attention_forward", "B4-H32-S4096-D128-fp16-causal", "flash_attention_forward", ("streaming/attention.py:flash_attention_fwd",), "source/triton/triton/attention/fused/06-fused-attention_runtime.py"),
    Entry("layer_norm", "8192x4096-fp16", "layer_norm_f16", ("normalization/layer_norm.py:layer_norm_f16",), "source/triton/triton/normalization/layer_norm/05-layer-norm_runtime.py"),
    Entry("flash_cross_entropy", "8192x32768-bf16", "flash_cross_entropy", ("loss/cross_entropy.py:flash_cross_entropy_bf16",), "source/triton/flash-attention/loss/cross_entropy/cross_entropy_runtime.py"),
    Entry("flash_layer_norm", "8192x4096-bf16", "flash_layer_norm", ("normalization/layer_norm.py:layer_norm_bf16",), "source/triton/flash-attention/normalization/layer_norm/layer_norm_runtime.py"),
    Entry("rotary_embedding", "B4-S4096-H32-D128-bf16", "rotary_embedding", ("position/rope.py:rotary_embedding_bf16",), "source/triton/flash-attention/position/rotary/rotary_runtime.py"),
    Entry("swiglu", "8192x14336-bf16", "swiglu_8192", ("activation/swiglu.py:swiglu_forward",), "source/triton/liger-kernel/activation/swiglu/swiglu_runtime.py"),
    Entry("embedding_lookup", "tokens16384-vocab32768-hidden4096-bf16", "embedding_lookup_v2", ("backward/embedding.py:embedding_forward_lookup_bf16",), "source/triton/liger-kernel/embedding/lookup/embedding_runtime.py"),
    Entry("cross_entropy", "8192x32768-bf16", "cross_entropy_bf16", ("loss/cross_entropy.py:fused_cross_entropy_bf16",), "source/triton/liger-kernel/loss/cross_entropy/cross_entropy_runtime.py"),
    Entry("padded_rope_cache_update", "B32-QH32-KVH8-D128-cache8192-fp16", "padded_rope_cache_update", ("position/rope_cache.py:padded_rope_cache_update",), "source/triton/xformers/position/rope_padded/rope_padded_kernels_runtime.py"),
    Entry("fused_add_rms_norm", "8192x4096-bf16", "fused_add_rms_norm_v2", ("normalization/fused_add_rms_norm.py:fused_add_rms_norm",), "source/triton/liger-kernel/normalization/fused_add_rms_norm/fused_add_rms_norm_runtime.py"),
    Entry("rms_norm", "8192x4096-bf16", "rms_norm_bf16", ("normalization/rms_norm.py:rms_norm_bf16",), "source/triton/liger-kernel/normalization/rms_norm/rms_norm_runtime.py"),
    Entry("xformers_rms_norm", "8192x4096-bf16", "xformers_rms_norm", ("normalization/rms_norm.py:rms_norm_bf16",), "source/triton/xformers/normalization/rms_norm/rmsnorm_kernels_runtime.py"),
    Entry("qkv_projection_pipeline", "M4096-K4096-QKV4096-fp16", "qkv_projection_pipeline", ("contraction/qkv.py:fused_qkv_projection",), "source/triton/xformers/gemm/tiled/tiled_matmul_kernels_runtime.py"),
    Entry("index_select", "source65536-selected32768-hidden4096-fp16", "index_select_v2", ("indexing/relations.py:index_select_rows",), "source/triton/xformers/indexing/index_select_cat/k_index_select_cat_runtime.py"),
    Entry("scaled_index_add", "destination65536-routed32768-hidden4096-fp16", "scaled_index_add_v2", ("indexing/relations.py:scaled_index_add_unique",), "source/triton/xformers/indexing/scaled_index_add/k_scaled_index_add_runtime.py"),
    Entry("scaled_fp8_splitk_gemm", "M4096-N14336-K4096-e4m3-split4", "scaled_fp8_splitk_gemm", ("contraction/block_scaled.py:scaled_fp8_splitk_matmul",), "source/triton/meta-applied-ai/gemm/fp8_scaled/scaled_fp8_gemm_runtime.py"),
    Entry("jagged_mean", "B512-T33024-D128-fp32", "jagged_mean", ("ragged/jagged_mean.py:jagged_mean",), "source/triton/tritonbench/ragged/jagged_mean/jagged_mean_runtime.py"),
    Entry("fp8_groupwise_quantize", "8192x4096-group128-bf16-e4m3", "bf16_groupwise_fp8_quantize", ("quantization/fp8.py:bf16_groupwise_fp8_quantize",), "source/triton/meta-applied-ai/quantization/fp8_groupwise/float8_groupwise_quant_runtime.py"),
    Entry("rope_qk", "B4-S4096-QH32-KVH8-D128-fp16", "rope_qk_v2", ("position/rope.py:rotary_qk_inplace",), "source/triton/liger-kernel/position/rope/rope_runtime.py"),
    Entry("causal_conv1d", "B4-C4096-S4096-W4-bf16-silu", "causal_conv1d_v2", ("convolution/direct.py:causal_depthwise_conv1d_bf16",), "source/triton/meta-applied-ai/convolution/causal_conv1d/causal_1d_conv_runtime.py"),
    Entry("varlen_causal_conv1d", "lengths2048-1536-1024-512-D4096-W4-bf16", "varlen_causal_conv1d", ("convolution/varlen.py:varlen_aligned_causal_depthwise_conv1d", "convolution/varlen.py:varlen_causal_conv1d_final_state"), "source/triton/fla/conv/causal1d/causal_conv_varlen_runtime.py"),
    Entry("causal_conv1d_update", "B32-D4096-W4-bf16", "causal_conv1d_update_v2", ("convolution/direct.py:causal_depthwise_conv1d_update_bf16",), "source/triton/fla/conv/causal1d/causal_conv_update_runtime.py"),
    Entry("modern_flash_attention_forward", "B2-H16-S2048-D128-fp16-causal", "modern_flash_attention_forward", ("streaming/attention.py:flash_attention_fwd",), "source/triton/meta-applied-ai/attention/flash_backward/flash_forward_runtime.py"),
    Entry("mamba3_siso_step", "B32-HQK4-H16-DQK32-DV64-bf16", "mamba3_siso_step", ("streaming/mamba.py:mamba3_siso_step",), "source/triton/state-spaces-mamba/mamba_ssm/ops/triton/mamba3/mamba3_siso_step_runtime.py"),
    Entry("flash_attention_backward", "B2-H16-S2048-D128-fp16-causal", "attention_backward_v2", ("backward/attention.py:attention_backward_delta", "backward/attention.py:attention_backward_dkdv", "backward/attention.py:attention_backward_dq"), "source/triton/meta-applied-ai/attention/flash_backward/flash_backward_runtime.py"),
    Entry("moe_expert_projection", "T2048-E8-top2-4096x14336-bf16", "moe_projection_v2", ("ragged/grouped_gemm.py:routed_expert_projection_bf16",), "source/triton/meta-applied-ai/moe/grouped/v0_moe_fused_runtime.py"),
    Entry("moe_splitk_expert_projection", "T2048-E8-top2-4096x14336-bf16", "moe_splitk_projection", ("ragged/grouped_gemm.py:routed_expert_projection_bf16",), "source/triton/meta-applied-ai/moe/splitk/v1_moe_fused_runtime.py"),
    Entry("mamba_chunk_state", "B1-S2048-H32-G8-P64-N128-C256-bf16", "mamba_chunk_state", ("streaming/mamba.py:mamba_chunk_state_bf16_fwd",), "source/triton/state-spaces-mamba/mamba_ssm/ops/triton/ssd_chunk_state_runtime.py"),
    Entry("mamba_state_passing", "B1-C8-H32-state8192-fp32", "mamba_state_passing", ("streaming/mamba.py:mamba_state_passing_fwd",), "source/triton/state-spaces-mamba/mamba_ssm/ops/triton/ssd_state_passing_runtime.py"),
    Entry("mamba_chunk_scan", "B1-S2048-H32-G8-P64-N128-C256-bf16", "mamba_chunk_scan_v2", ("streaming/selective_scan.py:mamba_chunk_scan_bf16_fwd",), "source/triton/state-spaces-mamba/mamba_ssm/ops/triton/ssd_chunk_scan_runtime.py"),
    Entry("mamba3_siso_forward", "B1-S2048-HQK4-H16-DQK32-DV64-bf16", "mamba3_siso_forward", ("streaming/mamba.py:mamba3_siso_forward",), "source/triton/state-spaces-mamba/mamba_ssm/ops/triton/mamba3/mamba3_siso_fwd_runtime.py"),
    Entry("paged_gqa_decode", "B16-QH32-KVH8-S8192-D128-page16-fp16", "paged_gqa_decode_v2", ("streaming/paged_attention.py:paged_gqa_decode_partials", "streaming/splitk_reduce.py:splitk_attention_bf16_to_f16_reduce"), "source/triton/vllm/attention/paged_decode/paged_gqa_decode_runtime.py"),
    Entry("splitk_paged_attention", "B16-QH32-KVH8-S8192-D128-page16-split8-fp16", "splitk_paged_attention", ("streaming/paged_attention.py:splitk_paged_gqa_decode_partials", "streaming/splitk_reduce.py:splitk_attention_weighted_sum_reduce"), "source/triton/xformers/attention/splitk/splitk_kernels_runtime.py"),
    Entry("paged_mla_decode", "B8-QH128-KVH1-S8192-C512-R64-page16-fp16", "paged_mla_decode_v2", ("streaming/mla.py:paged_mla_decode_partials", "streaming/splitk_reduce.py:splitk_attention_f32_to_f16_reduce"), "source/triton/vllm/attention/paged_decode/paged_mla_decode_runtime.py"),
    Entry("block_sparse_gqa_decode", "B8-QH32-KVH8-S8192-D128-blocks32x128", "block_sparse_gqa_decode_v2", ("streaming/block_sparse_attention.py:block_sparse_gqa_decode_partials", "streaming/block_sparse_attention.py:block_sparse_gqa_decode_combine"), "source/triton/vllm/attention/minimax_m3/sparse_decode_runtime.py"),
    Entry("flaggems_conv1d", "B64-L16384-K5-fp16-same", "flaggems_conv1d", ("convolution/direct.py:conv1d_same",), "source/triton/flag-gems/convolution/conv1d/conv1d_runtime.py"),
    Entry("flaggems_triangular_solve", "B4096-N16-fp32-lower", "flaggems_triangular_solve", ("factorization/triangular_solve.py:batched_lower_triangular_solve",), "source/triton/flag-gems/factorization/triangular_solve/linalg_solve_triangular_runtime.py"),
    Entry("flaggems_embedding_lookup", "tokens16384-vocab32768-hidden4096-bf16", "flaggems_embedding_lookup", ("backward/embedding.py:embedding_forward_lookup_bf16",), "source/triton/flag-gems/indexing/embedding/embedding_runtime.py"),
    Entry("flaggems_roll", "8192x4096-fp16-shift-1-axis0", "flaggems_roll", ("indexing/relations.py:roll_rows_forward",), "source/triton/flag-gems/indexing/roll/roll_runtime.py"),
    Entry("flaggems_transpose_copy", "4093x8191-fp16", "flaggems_transpose_copy", ("layout/transpose.py:matrix_transpose",), "source/triton/flag-gems/layout/copy/copy_runtime.py"),
    Entry("flaggems_batch_norm_training", "B32-C64-S4096-fp16", "flaggems_batch_norm_training", ("normalization/batch_norm.py:batch_norm_training",), "source/triton/flag-gems/normalization/batch_norm/batch_norm_runtime.py"),
    Entry("flaggems_group_norm_backward", "B32-C256-S1024-G32-fp16", "flaggems_group_norm_backward", ("backward/group_norm.py:group_norm_backward_dx", "backward/group_norm.py:group_norm_backward_weight_bias"), "source/triton/flag-gems/normalization/group_norm/groupnorm_runtime.py"),
    Entry("flaggems_logsumexp", "8192x8192-fp32", "flaggems_logsumexp", ("normalization/logsumexp.py:row_logsumexp",), "source/triton/flag-gems/normalization/logsumexp/logsumexp_runtime.py"),
    Entry("flaggems_softmax_backward", "4096x4097-fp32", "flaggems_softmax_backward", ("backward/softmax.py:softmax_backward",), "source/triton/flag-gems/normalization/softmax/softmax_runtime.py"),
    Entry("flaggems_fused_adamw", "N8388608-fp32", "flaggems_fused_adamw", ("optimization/adamw.py:adamw_update",), "source/triton/flag-gems/optimization/adamw/fused_adam_runtime.py"),
    Entry("flaggems_addcmul", "B64-C128-L4096-bf16", "flaggems_addcmul", ("activation/pointwise.py:addcmul_broadcast_bf16",), "source/triton/flag-gems/pointwise/addcmul/addcmul_runtime.py"),
    Entry("flaggems_fp8_mqa_logits", "Q256-K4096-H32-D128-e4m3", "flaggems_fp8_mqa_logits", ("routing/mqa_logits.py:fp8_mqa_logits",), "source/triton/flag-gems/routing/fp8_mqa_logits/fp8_mqa_logits_runtime.py"),
    Entry("flaggems_cumsum", "8192x8192-fp32-axis1", "flaggems_cumsum", ("streaming/ordered_prefix.py:row_cumsum_f32",), "source/triton/flag-gems/scan/cumsum/cumsum_runtime.py"),
    Entry("flaggems_histogram", "N8388608-bins256-fp32", "flaggems_histogram", ("statistics/histogram.py:histogram_256",), "source/triton/flag-gems/statistics/histogram/histc_runtime.py"),
    Entry("flaggems_max_pool2d_with_indices", "B8-C32-H128-W128-K3-S2-P1-fp16", "flaggems_max_pool2d_with_indices", ("vision/max_pool_with_indices.py:max_pool2d_with_indices",), "source/triton/flag-gems/vision/max_pool2d/max_pool2d_with_indices_runtime.py"),
    Entry("legacy_flash_attention_bias", "B4-H32-S4096-D128-fp16-vector-bias", "legacy_flash_attention_bias", ("streaming/attention.py:flash_attention_bias_fwd",), "source/triton/flash-attention/attention/fused/flash_attn_triton_runtime.py"),
)


CUTILE = (
    Entry("official_fmha", "B4-QH32-KVH8-S4096-D128-fp16-causal", "official_fmha", ("streaming/attention.py:flash_gqa_attention_fwd",), "source/cutile/cutile-python/attention/fmha/AttentionFMHA_runtime.py"),
    Entry("block_scaled_gemm", "M4096-N14336-K4096-fp8-block32", "block_scaled_gemm_v2", ("contraction/block_scaled.py:block_scaled_matmul",), "source/cutile/cutile-python/gemm/block_scaled/BlockScaledMatMul_runtime.py"),
    Entry("dense_gemm", "M4096-N14336-K4096-fp16", "dense_gemm", ("contraction/gemm.py:gemm",), "source/cutile/cutile-python/gemm/dense/MatMul_runtime.py"),
    Entry("moe_expert_projection", "T4096-E8-top2-4096x14336-bf16", "moe_projection_v2", ("ragged/grouped_gemm.py:routed_expert_projection_bf16",), "source/cutile/tilegym/moe/fused/moe_runtime.py"),
    Entry("layer_norm", "8192x4096-bf16", "layer_norm_bf16", ("normalization/layer_norm.py:layer_norm_bf16",), "source/cutile/cutile-python/normalization/layer_norm/LayerNorm_runtime.py"),
    Entry("silu_and_mul", "4096x28672-to14336-bf16", "silu_and_mul", ("activation/swiglu.py:silu_and_mul_packed",), "source/cutile/tilegym/activation/silu_and_mul/silu_and_mul_runtime.py"),
    Entry("attention_backward", "B2-QH8-KVH2-S1024-D64-fp16-causal", "attention_backward_cutile_v2", ("backward/attention.py:attention_backward_delta", "backward/attention.py:attention_backward_dkdv", "backward/attention.py:attention_backward_dq"), "source/cutile/tilegym/attention/dense/attention_backward_runtime.py"),
    Entry("dense_attention_forward", "B2-QH32-KVH8-S4096-D128-bf16-causal", "dense_attention_forward", ("streaming/attention.py:flash_gqa_attention_fwd",), "source/cutile/tilegym/attention/dense/attention_runtime.py"),
    Entry("grouped_flash_decode", "B8-QH32-KVH8-S8192-D128-bf16", "grouped_flash_decode", ("streaming/attention.py:grouped_flash_decode_partials", "streaming/splitk_reduce.py:splitk_attention_reduce"), "source/cutile/tilegym/attention/flash_decode/flash_decode_runtime.py"),
    Entry("swiglu", "8192x14336-bf16", "swiglu_8192", ("activation/swiglu.py:swiglu_forward",), "source/cutile/tilegym/activation/swiglu/swiglu_runtime.py"),
    Entry("splitk_attention_reduce", "B8-H32-S8192-splits16-D128", "splitk_attention_reduce_v2", ("streaming/splitk_reduce.py:splitk_attention_reduce",), "source/cutile/tilegym/attention/flash_decode/splitk_reduce_runtime.py"),
    Entry("mla_prefill", "B1-QH128-KVH1-S2048-D128-R64-fp16", "mla_prefill_v2", ("streaming/attention.py:mla_prefill",), "source/cutile/tilegym/attention/mla/mla_runtime.py"),
    Entry("batched_gemm", "B32-M512-N512-K1024-bf16", "batched_gemm_v2", ("contraction/batched_gemm.py:batched_gemm_nn",), "source/cutile/tilegym/gemm/batched/bmm_runtime.py"),
    Entry("tilegym_dense_gemm", "M8192-N11008-K4096-bf16", "tilegym_dense_gemm", ("contraction/gemm.py:bf16_gemm",), "source/cutile/tilegym/gemm/dense/matmul_runtime.py"),
    Entry("grouped_gemm", "rows256-512-1024-2048-K4096-N4096-bf16", "grouped_gemm_cutile_v2", ("ragged/grouped_gemm.py:ragged_grouped_gemm_bf16",), "source/cutile/tilegym/gemm/grouped/group_gemm_runtime.py"),
    Entry("moe_alignment", "T4096-top2-E64", "moe_alignment_v2", ("routing/moe_align.py:moe_count_routes", "routing/moe_align.py:moe_prefix_routes", "routing/moe_align.py:moe_scatter_routes", "routing/moe_align.py:moe_mark_expert_blocks"), "source/cutile/tilegym/moe/alignment/moe_align_block_runtime.py"),
    Entry("mhc_gemm_rms_scale", "T2048-H4096-streams4-bf16", "mhc_gemm_rms_scale", ("routing/mhc.py:mhc_gemm_rms_partial", "routing/mhc.py:mhc_gemm_rms_finalize"), "source/cutile/tilegym/mhc/fused/mhc_gemm_rms_runtime.py"),
    Entry("chunked_softmax", "8192x32768-bf16", "chunked_softmax_bf16", ("normalization/softmax.py:chunked_softmax_bf16",), "source/cutile/tilegym/normalization/softmax/softmax_runtime.py"),
    Entry("rope_qk", "B2-S4096-QH32-KVH8-D128-bf16", "rope_qk_bf16", ("position/rope.py:rotary_qk_bf16_inplace",), "source/cutile/tilegym/position/rope/rope_runtime.py"),
    Entry("gelu", "8192x4096-fp16-tanh", "gelu_tanh", ("activation/pointwise.py:gelu_tanh",), "source/cutile/tilegym/activation/fused/gelu_runtime.py"),
    Entry("geglu", "4096x28672-fp16-tanh", "geglu_tanh", ("activation/pointwise.py:geglu_tanh",), "source/cutile/tilegym/activation/fused/geglu_runtime.py"),
    Entry("relu", "8192x4096-fp16", "relu_forward", ("activation/pointwise.py:relu_forward",), "source/cutile/tilegym/activation/relu/relu_runtime.py"),
    Entry("dropout", "8192x4096-fp16-p0.1", "xor_shift_dropout", ("regularization/dropout.py:xor_shift_dropout",), "source/cutile/tilegym/regularization/dropout/dropout_runtime.py"),
    Entry("attention_sink_prefill", "B1-S4096-QH32-KVH8-D128-bf16", "attention_sink_prefill", ("streaming/attention_specialized.py:attention_sink_prefill",), "source/cutile/tilegym/attention/sink_prefill/attention_sink_runtime.py"),
    Entry("attention_sink_decode", "B32-S8192-QH32-KVH8-D128-bf16", "attention_sink_decode", ("streaming/attention_specialized.py:attention_sink_decode_partials", "streaming/splitk_reduce.py:splitk_attention_reduce"), "source/cutile/tilegym/attention/sink_decode/attention_sink_decode_runtime.py"),
    Entry("mhc_apply_residual", "T2048-H4096-streams4-bf16", "mhc_apply_residual", ("routing/mhc.py:mhc_apply_residual",), "source/cutile/tilegym/mhc/fused/mhc_apply_residual_runtime.py"),
    Entry("gemma_prefill", "B2-S4096-QH32-KVH8-D128-window1024-cap50-bf16", "gemma_prefill", ("streaming/attention_specialized.py:gemma_gqa_prefill",), "source/cutile/tilegym/attention/gemma_prefill/gemma_attention_runtime.py"),
    Entry("gemma_decode", "B32-S8192-QH32-KVH8-D128-window1024-cap50-bf16", "gemma_decode", ("streaming/attention_specialized.py:gemma_gqa_decode_partials", "streaming/splitk_reduce.py:splitk_attention_reduce"), "source/cutile/tilegym/attention/gemma_decode/gemma_attention_decode_runtime.py"),
    Entry("mhc_sinkhorn", "T8192-streams4-fp32", "mhc_sinkhorn", ("routing/mhc.py:mhc_sinkhorn",), "source/cutile/tilegym/mhc/fused/mhc_sinkhorn_runtime.py"),
    Entry("absorbed_mla_decode", "B8-H64-S8192-C512-R64-fp16", "absorbed_mla_decode", ("streaming/mla.py:absorbed_mla_decode",), "source/cutile/tilegym/attention/mla_decode/mla_decoding_runtime.py"),
    Entry("splitk_mla_decode", "B8-H64-S8192-C512-R64-split512-fp16", "splitk_mla_decode", ("streaming/mla.py:splitk_mla_decode_partials", "streaming/splitk_reduce.py:splitk_attention_reduce_f16"), "source/cutile/tilegym/attention/mla_decode_split/mla_decoding_split_kv_runtime.py"),
    Entry("sparse_mla_prefill", "S2048-SKV4096-H64-topk512-D128-R64-bf16", "sparse_mla_prefill_v2", ("streaming/mla.py:token_sparse_mla_value_prefill",), "source/cutile/tilegym/attention/sparse_mla/sparse_mla_runtime.py"),
    Entry("sliding_window_attention", "B2-S4096-QH32-KVH8-D128-window1024-fp16", "sliding_window_attention", ("streaming/attention_specialized.py:sliding_window_gqa_prefill",), "source/cutile/tilegym/attention/sliding_window/swa_attention_runtime.py"),
    Entry("rms_norm", "8192x4096-bf16", "rms_norm_bf16", ("normalization/rms_norm.py:rms_norm_bf16",), "source/cutile/tilegym/normalization/rms_norm/rms_norm_runtime.py"),
    Entry("recurrent_gated_delta", "B2-S2048-H8-K128-V128-bf16", "recurrent_gated_delta", ("streaming/gated_delta.py:recurrent_gated_delta_fwd",), "source/cutile/tilegym/scan/gated_delta_recurrent/recurrent_gated_delta_rule_runtime.py"),
    Entry("chunk_gated_delta", "B2-S2048-H8-K128-V128-C64-bf16", "chunk_gated_delta", ("streaming/gated_delta.py:chunk_gated_delta_prepare", "streaming/gated_delta.py:chunk_gated_delta_recurrence"), "source/cutile/tilegym/scan/gated_delta_chunk/chunk_gated_delta_rule_runtime.py"),
    Entry("nvfp4_quantize", "8192x4096-block16-bf16", "nvfp4_quantize", ("quantization/nvfp4.py:nvfp4_quantize", "quantization/nvfp4.py:encode_e2m1"), "source/cutile/tilegym/quantization/nvfp4/nvfp4_quantize_runtime.py"),
)


TILELANG = (
    Entry("block_sparse_gqa_decode", "B8-QH32-KVH8-S8192-D128-blocks128", "block_sparse_gqa_decode_tilelang", ("streaming/block_sparse_attention.py:block_sparse_gqa_decode_partials", "streaming/block_sparse_attention.py:block_sparse_gqa_decode_combine"), "source/tilelang/tilelang/attention/blocksparse_gqa_decode_varlen/example_tilelang_sparse_gqa_decode_varlen_indice_runtime.py"),
    Entry("dense_flash_attention", "B4-S4096-H32-D128-fp16-causal", "flash_attention_forward", ("streaming/attention.py:flash_attention_fwd",), "source/tilelang/tilelang/attention/flash_forward_bshd/example_mha_fwd_bshd_runtime.py"),
    Entry("varlen_gqa_prefill", "packed8-QH32-KVH8-D128-fp16-causal", "varlen_gqa_prefill_v2", ("streaming/attention.py:flash_varlen_gqa_prefill",), "source/tilelang/tilelang/attention/flash_forward_varlen/example_gqa_fwd_varlen_runtime.py"),
    Entry("gqa_decode", "B32-QH32-KVH8-S8192-D128-fp16", "gqa_decode_v2", ("streaming/attention.py:continuous_gqa_decode",), "source/tilelang/tilelang/attention/gqa_decode/example_gqa_decode_runtime.py"),
    Entry("varlen_gqa_decode_logits", "B16-QH32-KVH8-S4096-D64-fp16", "varlen_gqa_decode_logits_v2", ("streaming/attention.py:varlen_gqa_decode_with_sink_logits",), "source/tilelang/tilelang/attention/gqa_decode_varlen_logits/example_gqa_decode_varlen_logits_runtime.py"),
    Entry("paged_mla_decode", "B32-QH128-KVH1-S8192-V128-R64-page64-fp16", "paged_mla_decode_tilelang_v2", ("streaming/mla.py:paged_mla_decode",), "source/tilelang/tilelang/attention/mla_decode_paged/example_mla_decode_paged_runtime.py"),
    Entry("persistent_mla_decode", "B8-H64-S16384-C128-R64-split4-fp16", "persistent_mla_decode", (), "source/tilelang/tilelang/attention/mla_decode_persistent/example_mla_decode_persistent_runtime.py"),
    Entry("conv2d", "NHWC32x128x128x256-K3x3x256x512-fp16", "conv2d_tilelang_v2", ("convolution/direct.py:conv2d_nhwc",), "source/tilelang/tilelang/convolution/basic/example_convolution_runtime.py"),
    Entry("dense_gemm", "M4096-N14336-K4096-fp16", "dense_gemm", ("contraction/gemm.py:gemm",), "source/tilelang/tilelang/gemm/dense/example_gemm_runtime.py"),
    Entry("w4a8_gemm", "M4096-N14336-K4096-int8-int4", "w4a8_tilelang_v2", ("contraction/weight_only_int4.py:w4a8_packed_matmul",), "source/tilelang/tilelang/gemm/dequantize_w4a8/example_dequant_gemm_w4a8_runtime.py"),
    Entry("fp8_gemm", "M4096-N14336-K4096-e4m3", "fp8_gemm_tilelang_v2", ("contraction/weight_only_int4.py:fp8_e4m3_matmul",), "source/tilelang/tilelang/gemm/fp8/example_tilelang_gemm_fp8_runtime.py"),
    Entry("grouped_gemm", "rows256-512-1024-2048-K4096-N4096-fp16", "grouped_gemm_tilelang_v2", ("ragged/grouped_gemm.py:ragged_grouped_gemm",), "source/tilelang/tilelang/gemm/grouped/example_grouped_gemm_fwd_runtime.py"),
    Entry("sparse_2to4_gemm", "M8192-N14336-K8192-fp16", "sparse_2to4_tilelang_v2", ("contraction/sparse_2to4.py:sparse_2to4_gemm",), "source/tilelang/tilelang/gemm/sparse_2to4/example_gemm_sp_runtime.py"),
    Entry("deepgemm_fp8_2xacc", "M4096-N4096-K4096-e4m3-bf16", "deepgemm_fp8_2xacc", ("contraction/block_scaled.py:deepgemm_fp8_2xacc",), "source/tilelang/tilelang/gemm/fp8_2xacc/example_deepgemm_fp8_2xAcc_runtime.py"),
    Entry("online_softmax", "8192x8192-fp16", "online_softmax_f16", ("streaming/online_softmax.py:streamed_online_softmax_f16",), "source/tilelang/tilelang/normalization/online_softmax/online_softmax_runtime.py"),
    Entry("deepseek_topk_selector", "B32-S32768-topk2048-fp32", "deepseek_topk_selector", (), "source/tilelang/tilelang/routing/deepseek_v32_topk/topk_selector_runtime.py"),
    Entry("rms_norm", "8192x4096-fp32", "rms_norm_f32", ("normalization/rms_norm.py:rms_norm_f32",), "source/tilelang/tilelang/normalization/rms_norm/rms_norm_runtime.py"),
    Entry("mamba_chunk_scan", "B1-S2048-H32-G8-P64-N128-C256-fp16", "mamba_chunk_scan_v2", ("streaming/selective_scan.py:mamba_chunk_scan_fwd",), "source/tilelang/tilelang/scan/mamba_chunk_scan/example_mamba_chunk_scan_runtime.py"),
    Entry("mamba_chunk_state", "B1-S2048-H32-G8-P64-N128-C256-fp16", "mamba_chunk_state", ("streaming/mamba.py:mamba_chunk_state_fwd",), "source/tilelang/tilelang/scan/mamba_chunk_state/example_mamba_chunk_state_runtime.py"),
    Entry("linear_attention_forward", "B1-S2048-H16-D128-fp16", "linear_attention_forward", ("streaming/linear_attention.py:fused_chunk_linear_attention_fwd",), "source/tilelang/tilelang/linear_attention/fused_chunk_forward/example_linear_attn_fwd_runtime.py"),
    Entry("linear_attention_backward", "B1-S2048-H16-D128-fp16", "linear_attention_backward", ("streaming/linear_attention.py:fused_chunk_linear_attention_bwd",), "source/tilelang/tilelang/linear_attention/fused_chunk_backward/example_linear_attn_bwd_runtime.py"),
    Entry("retention_forward", "B1-S2048-H16-D128-fp16", "retention_forward", ("streaming/linear_attention.py:chunk_retention_fwd",), "source/tilelang/tilelang/linear_attention/retention/example_retention_fwd_runtime.py"),
    Entry("mhc_pre", "T2048-H4096-streams4-bf16", "mhc_pre", ("routing/mhc.py:mhc_pre_gemm_sqrsum", "routing/mhc.py:mhc_pre_fuse"), "source/tilelang/tilelang/mhc/pre/example_mhc_pre_runtime.py"),
    Entry("block_causal_attention", "B2-S4096-H16-D128-block64-fp16", "block_causal_attention", ("streaming/attention_specialized.py:block_causal_attention_fwd",), "source/tilelang/tilelang/attention/block_causal/block_causal_attention_runtime.py"),
    Entry("varlen_block_causal_attention", "lengths4096-3840-3584-3328-H16-D128-fp16", "varlen_block_causal_attention", ("streaming/attention_specialized.py:varlen_block_causal_attention_fwd",), "source/tilelang/tilelang/attention/block_causal_varlen/block_causal_attention_varlen_runtime.py"),
    Entry("native_sparse_attention_forward", "B2-S4096-QH32-KVH2-D128-blocks64", "native_sparse_attention_forward", ("streaming/attention_specialized.py:native_sparse_attention_fwd",), "source/tilelang/tilelang/attention/native_sparse_forward/example_tilelang_nsa_fwd_runtime.py"),
    Entry("native_sparse_attention_decode", "B8-S8192-QH32-KVH2-D128-blocks32", "native_sparse_attention_decode", ("streaming/attention_specialized.py:native_sparse_attention_fwd",), "source/tilelang/tilelang/attention/native_sparse_decode/example_tilelang_nsa_decode_runtime.py"),
    Entry("gqa_attention_backward", "B1-S4096-QH32-KVH8-D64-fp16-causal", "gqa_attention_backward_v2", ("backward/attention.py:attention_backward_delta", "backward/attention.py:attention_backward_dkdv", "backward/attention.py:attention_backward_dq"), "source/tilelang/tilelang/attention/gqa_backward/example_gqa_bwd_runtime.py"),
    Entry("sparse_mla_backward", "B1-S4096-SKV8192-H64-D576-topk2048-bf16", "sparse_mla_backward", ("backward/sparse_mla.py:sparse_mla_backward_delta", "backward/sparse_mla.py:sparse_mla_backward_main", "backward/sparse_mla.py:sparse_mla_grad_kv_cast"), "source/tilelang/tilelang/attention/sparse_mla_backward/sparse_mla_bwd_runtime.py"),
    Entry("fp8_lighting_indexer", "S4096-SKV8192-H32-D64-fp8", "fp8_lighting_indexer_v2", ("routing/mqa_logits.py:fp8_mqa_logits",), "source/tilelang/tilelang/attention/fp8_lighting_indexer/fp8_lighting_indexer_runtime.py"),
    Entry("per_token_fp8", "8192x8192-group128-f32-e4m3", "f32_groupwise_fp8_quantize", ("quantization/fp8.py:f32_groupwise_fp8_quantize",), "source/tilelang/tilelang/quantization/per_token_fp8/example_per_token_cast_to_fp8_runtime.py"),
    Entry("block_sparse_gemm", "M4096-N4096-K4096-block128x128x32-50pct", "block_sparse_gemm", ("contraction/block_sparse.py:block_sparse_matmul",), "source/tilelang/tilelang/gemm/block_sparse/example_blocksparse_gemm_runtime.py"),
    Entry("grouped_gemm_backward", "rows256-512-1024-2048-K4096-N4096-fp16", "grouped_gemm_backward", ("ragged/grouped_gemm.py:ragged_grouped_gemm_backward_weight",), "source/tilelang/tilelang/gemm/grouped_backward/example_grouped_gemm_bwd_runtime.py"),
    Entry("bitnet_int2_decode", "M1-N4096-K4096-int8-int2", "bitnet_int2_decode", ("contraction/weight_only_int4.py:bitnet_int2_matmul",), "source/tilelang/tilelang/gemm/bitnet_int2_decode/tilelang_bitnet_158_int8xint2_decode_runtime.py"),
    Entry("dequant_bf16_fp4", "M4096-N4096-K4096-bf16-fp4", "dequant_bf16_fp4", ("contraction/weight_only_int4.py:dequant_bf16_fp4_matmul",), "source/tilelang/tilelang/gemm/dequant_bf16_fp4/example_dequant_gemm_bf16_fp4_hopper_runtime.py"),
    Entry("block_fp4_quant", "8192x4096-block32-bf16", "block_fp4_quant", (), "source/tilelang/tilelang/quantization/block_fp4/act_quant_runtime.py"),
    Entry("mhc_post", "T4096-H2560-streams4-bf16", "mhc_post", ("routing/mhc.py:mhc_apply_residual",), "source/tilelang/tilelang/mhc/post/example_mhc_post_runtime.py"),
)


MOJO = (
    Entry("gemma_decode", "B32-QH32-KVH8-S8192-D128-window1024-bf16-8cores-host", "gemma_decode", ("streaming/attention_specialized.py:gemma_gqa_decode_partials", "streaming/splitk_reduce.py:splitk_attention_reduce"), "source/pytorch/cpu_runtime.py"),
    Entry("paged_gqa_decode", "B16-QH32-KVH8-S8192-D128-page16-split8-f16-8cores-host", "paged_gqa_decode", ("streaming/paged_attention.py:paged_gqa_decode_partials", "streaming/splitk_reduce.py:splitk_attention_f32_to_f16_reduce"), "source/pytorch/cpu_runtime.py"),
    Entry("block_sparse_gqa_decode", "B8-QH32-KVH8-S8192-D128-block32-selected128-split4-f16-8cores-host", "block_sparse_gqa_decode", ("streaming/block_sparse_attention.py:block_sparse_gqa_decode_partials", "streaming/block_sparse_attention.py:block_sparse_gqa_decode_combine"), "source/pytorch/cpu_runtime.py"),
    Entry("paged_mla_decode", "B32-QH128-KVH1-S8192-C128-R64-page64-f16-8cores-host", "paged_mla_decode", ("streaming/mla.py:paged_mla_decode",), "source/pytorch/cpu_runtime.py"),
    Entry("sparse_mla_backward", "B1-S4096-SKV8192-H64-DQ576-DV512-topk2048-bf16-8cores-host", "sparse_mla_backward", ("backward/sparse_mla.py:sparse_mla_backward_delta", "backward/sparse_mla.py:sparse_mla_backward_main", "backward/sparse_mla.py:sparse_mla_grad_kv_cast"), "source/pytorch/cpu_runtime.py"),
    Entry("sparse_2to4_gemm", "M8192-N14336-K8192-f16-f32-8cores-host", "sparse_2to4_gemm", ("contraction/sparse_2to4.py:sparse_2to4_gemm",), "source/pytorch/cpu_runtime.py"),
    Entry("nvfp4_quantize", "8192x4096-bf16-e2m1-e4m3-8cores-host", "nvfp4_quantize", ("quantization/nvfp4.py:nvfp4_quantize",), "source/pytorch/cpu_runtime.py"),
    Entry("reshape_and_cache", "T4096-H8-D128-blocks2048-page16-f16-8cores-host", "reshape_and_cache", ("cache/reshape_and_cache.py:reshape_and_cache",), "source/pytorch/cpu_runtime.py"),
    Entry("flaggems_fp8_mqa_logits", "Q256-K4096-H32-D128-f8-f32-8cores-host", "fp8_mqa_logits", ("routing/mqa_logits.py:fp8_mqa_logits",), "source/pytorch/cpu_runtime.py"),
    Entry("swiglu_forward_helper", "4096x14336-bf16-8cores-host", "swiglu_forward_helper", ("variants/activation.py:swiglu_forward_helper",), "source/pytorch/cpu_runtime.py"),
    Entry("gemm_loop_interchange", "M4096-K4096-N14336-f16-8cores-host", "gemm_loop_interchange", ("variants/contraction.py:gemm_loop_interchange",), "source/pytorch/cpu_runtime.py"),
    Entry("rotary_embedding_equivalent_index", "rows65536-D128-heads32-f16-8cores-host", "rotary_embedding_equivalent_index", ("variants/indexing.py:rotary_embedding_equivalent_index",), "source/pytorch/cpu_runtime.py"),
    Entry("matrix_transpose_scalar_domains", "4093x8191-f16-8cores-host", "matrix_transpose_scalar_domains", ("variants/layout.py:matrix_transpose_scalar_domains",), "source/pytorch/cpu_runtime.py"),
    Entry("stable_softmax_online", "8192x8192-f32-8cores-host", "stable_softmax_online", ("variants/normalization.py:stable_softmax_online",), "source/pytorch/cpu_runtime.py"),
    Entry("streamed_online_softmax_inline", "8192x8192-f32-8cores-host", "streamed_online_softmax_inline", ("variants/streaming.py:streamed_online_softmax_inline",), "source/pytorch/cpu_runtime.py"),
    Entry("batched_cholesky_right_looking", "B256-N16-f32-8cores-host", "batched_cholesky_right_looking", ("variants/decomposition.py:batched_cholesky_right_looking",), "source/pytorch/cpu_runtime.py"),
    Entry("mamba_chunk_state", "B1-L2048-H32-G8-P64-N128-C256-f16-8cores-host", "mamba_chunk_state_fwd", ("streaming/mamba.py:mamba_chunk_state_fwd",), "source/pytorch/cpu_runtime.py"),
    Entry("linear_attention_forward", "B1-S2048-H16-D128-f16-f32-8cores-host", "fused_chunk_linear_attention_fwd", ("streaming/linear_attention.py:fused_chunk_linear_attention_fwd",), "source/pytorch/cpu_runtime.py"),
    Entry("moe_expert_ffn", "T4096-D4096-F14336-E8-topk2-f16-f32-8cores-host", "moe_expert_ffn", ("ragged/moe.py:moe_expert_ffn",), "source/pytorch/cpu_runtime.py"),
    Entry("padded_rope_cache_update", "B32-QH32-KVH8-D128-cache8192-f16-8cores-host", "padded_rope_cache_update", ("position/rope_cache.py:padded_rope_cache_update",), "source/pytorch/cpu_runtime.py"),
    Entry("moe_alignment", "T4096-topk2-E64-block128-i32-8cores-host", "moe_alignment", ("routing/moe_align.py:moe_count_routes", "routing/moe_align.py:moe_prefix_routes", "routing/moe_align.py:moe_scatter_routes", "routing/moe_align.py:moe_mark_expert_blocks"), "source/pytorch/cpu_runtime.py"),
    Entry("mhc_post", "T4096-H2560-streams4-bf16-8cores-host", "mhc_post", ("routing/mhc.py:mhc_apply_residual",), "source/pytorch/cpu_runtime.py"),
    Entry("attention_backward", "B2-HQ8-HK2-S1024-D64-f16-8cores-host", "attention_backward", ("backward/attention.py:attention_backward_delta", "backward/attention.py:attention_backward_dkdv", "backward/attention.py:attention_backward_dq"), "source/pytorch/cpu_runtime.py"),
    Entry("mxfp8_gemm", "M4096-K4096-N14336-group32-e4m3-e8m0-f32-8cores-host", "block_scaled_matmul", ("contraction/block_scaled.py:block_scaled_matmul",), "source/pytorch/cpu_runtime.py"),
    Entry("block_sparse_gemm", "M4096-K4096-N4096-block128x128x32-f16-8cores-host", "block_sparse_matmul", ("contraction/block_sparse.py:block_sparse_matmul",), "source/pytorch/cpu_runtime.py"),
    Entry("mamba_chunk_scan", "B1-L2048-H32-G8-P64-N128-C256-f16-8cores-host", "mamba_chunk_scan_fwd", ("streaming/selective_scan.py:mamba_chunk_scan_fwd",), "source/pytorch/cpu_runtime.py"),
    Entry("layer_norm_backward", "4096x4096-partial128-bf16-8cores-host", "layer_norm_backward", ("backward/layer_norm.py:layer_norm_backward_rows", "backward/layer_norm.py:layer_norm_backward_reduce"), "source/pytorch/cpu_runtime.py"),
    Entry("group_norm_backward", "B32-C256-S1024-G32-f16-8cores-host", "group_norm_backward", ("backward/group_norm.py:group_norm_backward_dx", "backward/group_norm.py:group_norm_backward_weight_bias"), "source/pytorch/cpu_runtime.py"),
    Entry("qkv_projection", "P3-T4096-K4096-N4096-f16-8cores-host", "qkv_projection_pipeline", ("contraction/qkv.py:fused_qkv_projection",), "source/pytorch/cpu_runtime.py"),
    Entry("dropout", "8192x4096-f16-seed12345-p0.1-8cores-host", "dropout", ("regularization/dropout.py:xor_shift_dropout",), "source/pytorch/cpu_runtime.py"),
    Entry("unique_consecutive", "64x4096-i32-8cores-host", "unique_consecutive", ("compaction/unique_consecutive.py:unique_consecutive_rows",), "source/pytorch/cpu_runtime.py"),
    Entry("flash_attention_bf16", "B2-HQ32-HK8-S4096-D128-bf16-8cores-host", "flash_attention_bf16_fwd", ("streaming/attention.py:flash_attention_bf16_fwd",), "source/pytorch/cpu_runtime.py"),
    Entry("ragged_grouped_gemm", "R8192-G8-K4096-N4096-f16-8cores-host", "ragged_grouped_gemm", ("ragged/grouped_gemm.py:ragged_grouped_gemm",), "source/pytorch/cpu_runtime.py"),
    Entry("nested_jagged_mean_pool", "D256-S4096-T65536-F128-f32-8cores-host", "nested_jagged_mean_pool", ("ragged/nested_pool.py:nested_jagged_mean_pool",), "source/pytorch/cpu_runtime.py"),
    Entry("jagged_mean", "B512-T33024-D128-f32-8cores-host", "jagged_mean", ("ragged/jagged_mean.py:jagged_mean",), "source/pytorch/cpu_runtime.py"),
    Entry("selective_state_scan", "B128-L4096-f32-8cores-host", "selective_state_scan", ("streaming/selective_scan.py:selective_state_scan",), "source/pytorch/cpu_runtime.py"),
    Entry("streamed_online_softmax_f16", "8192x8192-f16-8cores-host", "streamed_online_softmax_f16", ("streaming/online_softmax.py:streamed_online_softmax_f16",), "source/pytorch/cpu_runtime.py"),
    Entry("recurrent_gated_delta_fwd", "B2-T2048-H8-K128-V128-bf16-8cores-host", "recurrent_gated_delta_fwd", ("streaming/gated_delta.py:recurrent_gated_delta_fwd",), "source/pytorch/cpu_runtime.py"),
    Entry("fp8_gemm", "M4096-N14336-K4096-f8e4m3fn-8cores-host", "fp8_gemm", ("contraction/weight_only_int4.py:fp8_e4m3_matmul",), "source/pytorch/cpu_runtime.py"),
    Entry("silu_and_mul_packed", "4096x28672-bf16-8cores-host", "silu_and_mul_packed", ("activation/swiglu.py:silu_and_mul_packed",), "source/pytorch/cpu_runtime.py"),
    Entry("geglu_tanh", "4096x28672-f16-8cores-host", "geglu_tanh", ("activation/pointwise.py:geglu_tanh",), "source/pytorch/cpu_runtime.py"),
    Entry("rope_qk_partial", "B4-S2048-QH32-KH8-D128-R64-f16-8cores-host", "rope_qk_partial", ("position/rope.py:rotary_qk_partial_inplace",), "source/pytorch/cpu_runtime.py"),
    Entry("rotary_embedding_bf16", "B4-S4096-H32-D128-bf16-8cores-host", "rotary_embedding_bf16", ("position/rope.py:rotary_embedding_bf16",), "source/pytorch/cpu_runtime.py"),
    Entry("rope_qk_bf16_inplace", "B2-S4096-QH32-KH8-D128-bf16-8cores-host", "rope_qk_bf16_inplace", ("position/rope.py:rotary_qk_bf16_inplace",), "source/pytorch/cpu_runtime.py"),
    Entry("fp8_groupwise_quantize", "8192x4096-bf16-group128-f8e4m3fn-8cores-host", "fp8_groupwise_quantize", ("quantization/fp8.py:bf16_groupwise_fp8_quantize",), "source/pytorch/cpu_runtime.py"),
    Entry("partitioned_two_pass_max", "M128-N257-P300-f32-8cores-host", "partitioned_two_pass_max", ("reduction/two_pass.py:partitioned_max_partial", "reduction/two_pass.py:partitioned_max_reduce"), "source/pytorch/cpu_runtime.py"),
    Entry("shifted_row_copy", "4096x1024-f32-8cores-host", "shifted_row_copy", ("indexing/relations.py:shifted_row_copy",), "source/pytorch/cpu_runtime.py"),
    Entry("roll_rows_forward", "8192x4096-f16-flat-8cores-host", "roll_rows_forward", ("indexing/relations.py:roll_rows_forward",), "source/pytorch/cpu_runtime.py"),
    Entry("grouped_query_head_add", "QH32-KH8-T4096-f16-8cores-host", "grouped_query_head_add", ("indexing/relations.py:grouped_query_head_add",), "source/pytorch/cpu_runtime.py"),
    Entry("alternating_signed_indices", "4093x8191-i32-8cores-host", "alternating_signed_indices", ("pointwise/select.py:alternating_signed_indices",), "source/pytorch/cpu_runtime.py"),
    Entry("boolean_reduction", "8192x4093-i32-8cores-host", "row_boolean_reduction", ("reduction/boolean.py:row_boolean_reduction",), "source/pytorch/cpu_runtime.py"),
    Entry("kmeans_assign", "points65536-clusters64-features64-f16-8cores-host", "kmeans_assign", ("clustering/kmeans.py:kmeans_assign",), "source/pytorch/cpu_runtime.py"),
    Entry("fused_cross_entropy", "4096x16384-f32-8cores-host", "fused_cross_entropy", ("loss/cross_entropy.py:fused_cross_entropy",), "source/pytorch/cpu_runtime.py"),
    Entry("group_norm_silu_backward", "B32-C256-S1024-G32-bf16-8cores-host", "group_norm_silu_backward", ("backward/group_norm_silu.py:group_norm_silu_backward",), "source/pytorch/cpu_runtime.py"),
    Entry("causal_conv1d", "B8-C2048-L4096-W4-f16-8cores-host", "causal_conv1d", ("convolution/direct.py:causal_depthwise_conv1d",), "source/pytorch/cpu_runtime.py"),
    Entry("conv2d", "B16-H256-W256-K3-f16-8cores-host", "conv2d", ("convolution/direct.py:conv2d_same",), "source/pytorch/cpu_runtime.py"),
    Entry("causal_conv1d_backward", "B8-C2048-L4096-W4-f16-8cores-host", "causal_conv1d_backward", ("backward/causal_conv.py:causal_conv1d_backward_partials", "backward/causal_conv.py:causal_conv1d_backward_reduce"), "source/pytorch/cpu_runtime.py"),
    Entry("batch_norm_training", "B32-C64-S4096-fp16-8cores-host", "batch_norm_training", ("normalization/batch_norm.py:batch_norm_training",), "source/pytorch/cpu_runtime.py"),
    Entry("insertion_top_k", "1024x4093-k8-fp32-8cores-host", "insertion_top_k", ("sampling/top_k.py:insertion_top_k",), "source/pytorch/cpu_runtime.py"),
    Entry("histogram", "N8388608-bins256-f32-to-i32-8cores-host", "histogram_256", ("statistics/histogram.py:histogram_256",), "source/pytorch/cpu_runtime.py"),
    Entry("cholesky", "B256-N16-fp32-8cores-host", "batched_cholesky_lower", ("factorization/cholesky.py:batched_cholesky_lower",), "source/pytorch/cpu_runtime.py"),
    Entry("householder_qr", "B128-R32-C16-fp32-8cores-host", "batched_householder_qr", ("factorization/householder_qr.py:batched_householder_qr",), "source/pytorch/cpu_runtime.py"),
    Entry("causal_conv_update", "B64-D4096-W4-fp16-8cores-host", "causal_depthwise_conv1d_update", ("convolution/direct.py:causal_depthwise_conv1d_update",), "source/pytorch/cpu_runtime.py"),
    Entry("sorted_nucleus_cutoff", "1024x4093-fp32-8cores-host", "sorted_nucleus_cutoff", ("sampling/nucleus.py:sorted_nucleus_cutoff",), "source/pytorch/cpu_runtime.py"),
    Entry("flaggems_cumsum", "8192x8192-fp32-8cores-host", "row_cumsum_f32", ("streaming/ordered_prefix.py:row_cumsum_f32",), "source/pytorch/cpu_runtime.py"),
    Entry("ordered_prefix", "512x17x31-fp32-8cores-host", "ordered_product_prefix", ("streaming/ordered_prefix.py:ordered_product_prefix",), "source/pytorch/cpu_runtime.py"),
    Entry("compact_nonzero", "64x4096-fp32-8cores-host", "compact_nonzero_rows", ("compaction/nonzero.py:compact_nonzero_rows",), "source/pytorch/cpu_runtime.py"),
    Entry("varlen_causal_conv1d", "U5120-D4096-W4-bf16-8cores-host", "varlen_aligned_causal_depthwise_conv1d + varlen_causal_conv1d_final_state", ("convolution/varlen.py:varlen_aligned_causal_depthwise_conv1d", "convolution/varlen.py:varlen_causal_conv1d_final_state"), "source/pytorch/cpu_runtime.py"),
    Entry("radix2_fft", "B1024-N1024-fp32-complex-8cores-host", "radix2_fft", ("spectral/fft.py:radix2_fft",), "source/pytorch/cpu_runtime.py"),
    Entry("viterbi", "B64-T256-S64-fp32-8cores-host", "viterbi_decode", ("dynamic_programming/viterbi.py:viterbi_decode",), "source/pytorch/cpu_runtime.py"),
    Entry("smith_waterman", "B128-Q128-R128-i32-8cores-host", "smith_waterman_score", ("dynamic_programming/smith_waterman.py:smith_waterman_score",), "source/pytorch/cpu_runtime.py"),
    Entry("bitonic_sort", "4096x256-fp32-8cores-host", "bitonic_sort_rows", ("sorting/bitonic.py:bitonic_sort_rows",), "source/pytorch/cpu_runtime.py"),
    Entry("flaggems_triangular_solve", "B4096-N16-fp32-lower-8cores-host", "batched_lower_triangular_solve", ("factorization/triangular_solve.py:batched_lower_triangular_solve",), "source/pytorch/cpu_runtime.py"),
    Entry("flaggems_conv1d", "B64-L16384-K5-fp16-same-8cores-host", "conv1d_same", ("convolution/direct.py:conv1d_same",), "source/pytorch/cpu_runtime.py"),
    Entry("swiglu", "8192x14336-bf16-8cores-host", "swiglu_forward", ("activation/swiglu.py:swiglu_forward",), "source/pytorch/cpu_runtime.py"),
    Entry("embedding_lookup", "tokens16384-vocab32768-hidden4096-bf16-8cores-host", "embedding_forward_lookup_bf16", ("backward/embedding.py:embedding_forward_lookup_bf16",), "source/pytorch/cpu_runtime.py"),
    Entry("embedding_lookup_f32", "tokens8192-vocab8192-hidden1021-f32-8cores-host", "embedding_forward_lookup", ("backward/embedding.py:embedding_forward_lookup",), "source/pytorch/cpu_runtime.py"),
    Entry("embedding_backward_atomic", "M32768-V8192-D1021-f32-8cores-host", "embedding_backward_atomic", ("backward/embedding.py:embedding_backward_atomic",), "source/pytorch/cpu_runtime.py"),
    Entry("atomic_compare_exchange", "N65536-i32-8cores-host", "claim_zero_slots", ("synchronization/compare_exchange.py:claim_zero_slots",), "source/pytorch/cpu_runtime.py"),
    Entry("index_select", "source65536-selected32768-hidden4096-fp16-8cores-host", "index_select_rows", ("indexing/relations.py:index_select_rows",), "source/pytorch/cpu_runtime.py"),
    Entry("flaggems_fused_adamw", "N8388608-fp32-8cores-host", "adamw_update", ("optimization/adamw.py:adamw_update",), "source/pytorch/cpu_runtime.py"),
    Entry("adafactor", "4096x4096-fp32-8cores-host", "adafactor", ("optimization/adafactor.py:adafactor_update_rows", "optimization/adafactor.py:adafactor_update_columns", "optimization/adafactor.py:adafactor_apply"), "source/pytorch/cpu_runtime.py"),
    Entry("dense_gemm", "M4096-N14336-K4096-fp16-8cores-host", "gemm", ("contraction/gemm.py:gemm",), "source/pytorch/cpu_runtime.py"),
    Entry("tilegym_dense_gemm", "M8192-N11008-K4096-bf16-8cores-host", "bf16_gemm", ("contraction/gemm.py:bf16_gemm",), "source/pytorch/cpu_runtime.py"),
    Entry("batched_gemm", "B32-M512-N512-K1024-bf16-8cores-host", "batched_gemm_nn", ("contraction/batched_gemm.py:batched_gemm_nn",), "source/pytorch/cpu_runtime.py"),
    Entry("batched_gemm_tn", "B32-M512-N512-K1024-bf16-TN-8cores-host", "batched_gemm_tn", ("contraction/batched_gemm.py:batched_gemm_tn",), "source/pytorch/cpu_runtime.py"),
    Entry("batched_gemm_nt", "B32-M512-N512-K1024-bf16-NT-8cores-host", "batched_gemm_nt", ("contraction/batched_gemm.py:batched_gemm_nt",), "source/pytorch/cpu_runtime.py"),
    Entry("batched_gemm_tt", "B32-M512-N512-K1024-bf16-TT-8cores-host", "batched_gemm_tt", ("contraction/batched_gemm.py:batched_gemm_tt",), "source/pytorch/cpu_runtime.py"),
    Entry("mla_head_query_projection", "B1-Q512-H8-I128-O512-fp16-8cores-host", "mla_head_query_projection", ("contraction/mla.py:mla_head_projection",), "source/pytorch/cpu_runtime.py"),
    Entry("mla_head_value_projection", "B1-Q512-H8-I512-O128-fp16-8cores-host", "mla_head_value_projection", ("contraction/mla.py:mla_head_projection",), "source/pytorch/cpu_runtime.py"),
    Entry("fused_softmax", "8192x8192-fp16-8cores-host", "stable_softmax_f16", ("normalization/softmax.py:stable_softmax_f16",), "source/pytorch/cpu_runtime.py"),
    Entry("chunked_softmax", "8192x32768-bf16-8cores-host", "chunked_softmax_bf16", ("normalization/softmax.py:chunked_softmax_bf16",), "source/pytorch/cpu_runtime.py"),
    Entry("layer_norm_f16", "8192x4096-fp16-8cores-host", "layer_norm_f16", ("normalization/layer_norm.py:layer_norm_f16",), "source/pytorch/cpu_runtime.py"),
    Entry("layer_norm_bf16", "8192x4096-bf16-8cores-host", "layer_norm_bf16", ("normalization/layer_norm.py:layer_norm_bf16",), "source/pytorch/cpu_runtime.py"),
    Entry("rms_norm_f32", "8192x4096-f32-8cores-host", "rms_norm_f32", ("normalization/rms_norm.py:rms_norm_f32",), "source/pytorch/cpu_runtime.py"),
    Entry("rms_norm_bf16", "8192x4096-bf16-8cores-host", "rms_norm_bf16", ("normalization/rms_norm.py:rms_norm_bf16",), "source/pytorch/cpu_runtime.py"),
    Entry("flaggems_softmax_backward", "4096x4097-fp32-8cores-host", "softmax_backward", ("backward/softmax.py:softmax_backward",), "source/pytorch/cpu_runtime.py"),
    Entry("flaggems_transpose_copy", "4093x8191-fp16-8cores-host", "matrix_transpose", ("layout/transpose.py:matrix_transpose",), "source/pytorch/cpu_runtime.py"),
    Entry("gelu", "8192x4096-fp16-tanh-8cores-host", "gelu_tanh", ("activation/pointwise.py:gelu_tanh",), "source/pytorch/cpu_runtime.py"),
    Entry("relu", "8192x4096-fp16-8cores-host", "relu_forward", ("activation/pointwise.py:relu_forward",), "source/pytorch/cpu_runtime.py"),
    Entry("flaggems_addcmul", "B64-C128-L4096-bf16-8cores-host", "addcmul_broadcast_bf16", ("activation/pointwise.py:addcmul_broadcast_bf16",), "source/pytorch/cpu_runtime.py"),
    Entry("flaggems_logsumexp", "8192x8192-fp32-8cores-host", "row_logsumexp", ("normalization/logsumexp.py:row_logsumexp",), "source/pytorch/cpu_runtime.py"),
    Entry("scalar_table_lookup", "C65536-D128-M65536-i32-f32-8cores-host", "scalar_table_lookup", ("indexing/relations.py:scalar_table_lookup",), "source/pytorch/cpu_runtime.py"),
    Entry("csr_spmv", "32768x32768-nnz32-fp32-8cores-host", "csr_spmv", ("sparse/csr_spmv.py:csr_spmv",), "source/pytorch/cpu_runtime.py"),
    Entry("csr_spmm", "8192x8192-nnz32-features128-fp32-8cores-host", "csr_spmm", ("sparse/csr_spmm.py:csr_spmm",), "source/pytorch/cpu_runtime.py"),
    Entry("roi_align_center_sample", "B8-C64-H128-W128-R2048-7x7-fp32-8cores-host", "roi_align_center_sample", ("vision/roi_align.py:roi_align_center_sample",), "source/pytorch/cpu_runtime.py"),
    Entry("max_pool2d", "B8-C32-H128-W128-K3-S2-P1-fp16-8cores-host", "max_pool2d", ("vision/max_pool.py:max_pool2d",), "source/pytorch/cpu_runtime.py"),
    Entry("flaggems_max_pool2d_with_indices", "B8-C32-H128-W128-K3-S2-P1-fp16-8cores-host", "max_pool2d_with_indices", ("vision/max_pool_with_indices.py:max_pool2d_with_indices",), "source/pytorch/cpu_runtime.py"),
    Entry("integer_log2_floor", "N262144-i32-8cores-host", "integer_log2_floor", ("pointwise/while_loop.py:integer_log2_floor",), "source/pytorch/cpu_runtime.py"),
    Entry("rope_qk", "B4-S4096-QH32-KVH8-D128-fp16-8cores-host", "rotary_qk_inplace", ("position/rope.py:rotary_qk_inplace",), "source/pytorch/cpu_runtime.py"),
    Entry("greedy_nms", "B32-N1024-fp32-8cores-host", "greedy_nms", ("vision/nms.py:greedy_nms",), "source/pytorch/cpu_runtime.py"),
    Entry("causal_attention_f32", "B8-S128-D32-f32-8cores", "causal_attention_f32", ("streaming/attention_f32.py:causal_attention_f32",), "source/mojo/intentdsl/attention/causal/causal_runtime.py"),
    Entry("causal_linear_attention_f32", "B8-S128-D32-f32-8cores", "causal_linear_attention_f32", ("streaming/attention_f32.py:causal_linear_attention_f32",), "source/mojo/intentdsl/attention/linear/linear_runtime.py"),
    Entry("batched_row_affine", "17x257x4093-f32-8cores", "batched_row_affine", ("pointwise/batched_affine.py:batched_row_affine",), "source/mojo/modular/pointwise/batched_affine/batched_affine_runtime.py"),
    Entry("weighted_rms_norm", "8192x4096-f32-8cores", "weighted_rms_norm", ("normalization/rms_norm.py:weighted_rms_norm",), "source/mojo/modular/normalization/rms_norm/rms_norm_runtime.py"),
    Entry("dense_gemm_f32", "M1024-N1024-K1024-f32-8cores", "gemm_f32", ("contraction/gemm.py:gemm_f32",), "source/mojo/modular/contraction/gemm/gemm_runtime.py"),
    Entry("stable_softmax", "8192x8192-f32-8cores", "stable_softmax", ("normalization/softmax.py:stable_softmax",), "source/mojo/modular/normalization/softmax/softmax_runtime.py"),
    Entry("weighted_layer_norm", "8192x4096-f32-8cores", "weighted_layer_norm", ("normalization/layer_norm.py:weighted_layer_norm",), "source/mojo/modular/normalization/layer_norm/layer_norm_runtime.py"),
    Entry("swiglu_backward", "4096x4096-bf16-8cores-host", "swiglu_backward", ("backward/swiglu.py:swiglu_backward",), "source/pytorch/cpu_runtime.py"),
    Entry("fused_add_rms_norm", "8192x4096-bf16-8cores-host", "fused_add_rms_norm", ("normalization/fused_add_rms_norm.py:fused_add_rms_norm",), "source/pytorch/cpu_runtime.py"),
    Entry("paired_sum_product", "N1048576-f32-8cores-host", "paired_sum_product", ("pointwise/record.py:paired_sum_product",), "source/pytorch/cpu_runtime.py"),
    Entry("gated_dual_gemm", "M2048-N4096-K4096-fp16-8cores-host", "gated_dual_gemm", ("contraction/dual_gemm.py:gated_dual_gemm",), "source/pytorch/cpu_runtime.py"),
    Entry("dropout_residual_rms_norm", "4096x4096-bf16-seed17-p0.1-8cores-host", "dropout_residual_rms_norm", ("normalization/dropout_residual_rms_norm.py:dropout_residual_rms_norm_forward", "normalization/dropout_residual_rms_norm.py:dropout_residual_rms_norm_backward_data"), "source/pytorch/cpu_runtime.py"),
    Entry("barrier_option_paths", "paths262144-steps64-f32-seed17-8cores-host", "barrier_option_paths", ("simulation/monte_carlo.py:barrier_option_paths",), "source/pytorch/cpu_runtime.py"),
)


WEFT = (
    Entry("i8_gemv_bias", "M1-N4096-K4096-i8-i32-IME1-1core", "gemm_i8", ("contraction/gemm.py:gemm_i8",), "source/weft/intentdsl/contraction/i8/i8_runtime.py", "weft/ime.json"),
    Entry("i8_gemm_bias", "M128-N4096-K4096-i8-i32-IME1-1core", "gemm_i8", ("contraction/gemm.py:gemm_i8",), "source/weft/intentdsl/contraction/i8/i8_runtime.py", "weft/ime.json"),
    Entry("causal_attention_f32", "B8-S128-D32-f32-1core", "causal_attention_f32", ("streaming/attention_f32.py:causal_attention_f32",), "source/weft/intentdsl/attention/attention_runtime.py"),
    Entry("causal_linear_attention_f32", "B8-S128-D32-f32-1core", "causal_linear_attention_f32", ("streaming/attention_f32.py:causal_linear_attention_f32",), "source/weft/intentdsl/attention/attention_runtime.py"),
    Entry("q4_k_projection", "N4096-K4096-Q4_K-f32-1core", "quantized_projection",
          ("quantization/quantized_projection.py:quantized_projection",),
          "source/weft/tianchenrv/contraction/q4_k_projection/q4_k_projection_runtime.py"),
    Entry("q4_k_projection_ime", "N4096-K4096-Q4_K-f32-IME1-1core", "quantized_projection",
          ("quantization/quantized_projection.py:quantized_projection",),
          "source/weft/tianchenrv/contraction/q4_k_projection/q4_k_projection_runtime.py", "weft/ime.json"),
)


BY_PROVIDER = {
    "triton": TRITON,
    "cutile": CUTILE,
    "tilelang": TILELANG,
    "mojo": MOJO,
    "weft": WEFT,
}
