module attributes {intent.source_module = "sum_absolute", intent_gpu.physical} {
  func.func @__intent_gpu_sum_absolute(%arg0: !intent_gpu.view<f32, 2, 0, 0, 1, <[#intent_gpu.expr<2, 1, "D1", []>, #intent_gpu.expr<2, 1, "D1", []>], [1, 1], true, ["S0_0", "S0_1"], "", false>> {intent_gpu.abi_kind = "view", intent_gpu.abi_name = "values"}, %arg1: !intent_gpu.view<f32, 0, 1, 1, 2, <[], [], true, [], "", false>> {intent_gpu.abi_kind = "view", intent_gpu.abi_name = "output"}, %arg2: index {intent_gpu.abi_kind = "dimension", intent_gpu.abi_name = "D1", intent_gpu.dimension = 1 : i64, intent_gpu.source_abi = 0 : i64, intent_gpu.source_axis = 0 : i64}, %arg3: index {intent_gpu.abi_kind = "stride", intent_gpu.abi_name = "S0_0", intent_gpu.source_abi = 0 : i64, intent_gpu.source_axis = 0 : i64}, %arg4: index {intent_gpu.abi_kind = "stride", intent_gpu.abi_name = "S0_1", intent_gpu.source_abi = 0 : i64, intent_gpu.source_axis = 1 : i64}) attributes {intent_gpu.capabilities = #intent_gpu.capabilities<170, 102400, 101376, 65536, 1024, 12, 0, true, false>, intent_gpu.effect_origins = [5], intent_gpu.grid_rank = 1 : i64, intent_gpu.kernel, intent_gpu.origin = "/home/kingdom/phdworks/intentdsl/report/agent-tritonbench/refined/programs/symmetric_mm_and_abs_sum/intent/repeat-0/generation-5/candidate.py:34:1", intent_gpu.program_space = [#intent_gpu.expr<0, 1, "", []>], intent_gpu.shared.config_tuples = [{REDUCE_CHUNK_1_A0 = 32 : i64, REDUCE_CHUNK_1_A1 = 512 : i64}, {REDUCE_CHUNK_1_A0 = 16 : i64, REDUCE_CHUNK_1_A1 = 1024 : i64}, {REDUCE_CHUNK_1_A0 = 64 : i64, REDUCE_CHUNK_1_A1 = 256 : i64}], intent_gpu.triton.configs = [{num_ctas = 1 : i64, num_stages = 2 : i64, num_warps = 8 : i64, parameters = {REDUCE_CHUNK_1_A0 = 32 : i64, REDUCE_CHUNK_1_A1 = 512 : i64}}, {num_ctas = 1 : i64, num_stages = 2 : i64, num_warps = 4 : i64, parameters = {REDUCE_CHUNK_1_A0 = 32 : i64, REDUCE_CHUNK_1_A1 = 512 : i64}}, {num_ctas = 1 : i64, num_stages = 2 : i64, num_warps = 16 : i64, parameters = {REDUCE_CHUNK_1_A0 = 32 : i64, REDUCE_CHUNK_1_A1 = 512 : i64}}, {num_ctas = 1 : i64, num_stages = 2 : i64, num_warps = 8 : i64, parameters = {REDUCE_CHUNK_1_A0 = 16 : i64, REDUCE_CHUNK_1_A1 = 1024 : i64}}, {num_ctas = 1 : i64, num_stages = 2 : i64, num_warps = 4 : i64, parameters = {REDUCE_CHUNK_1_A0 = 16 : i64, REDUCE_CHUNK_1_A1 = 1024 : i64}}, {num_ctas = 1 : i64, num_stages = 2 : i64, num_warps = 16 : i64, parameters = {REDUCE_CHUNK_1_A0 = 16 : i64, REDUCE_CHUNK_1_A1 = 1024 : i64}}, {num_ctas = 1 : i64, num_stages = 2 : i64, num_warps = 8 : i64, parameters = {REDUCE_CHUNK_1_A0 = 64 : i64, REDUCE_CHUNK_1_A1 = 256 : i64}}, {num_ctas = 1 : i64, num_stages = 2 : i64, num_warps = 4 : i64, parameters = {REDUCE_CHUNK_1_A0 = 64 : i64, REDUCE_CHUNK_1_A1 = 256 : i64}}, {num_ctas = 1 : i64, num_stages = 2 : i64, num_warps = 16 : i64, parameters = {REDUCE_CHUNK_1_A0 = 64 : i64, REDUCE_CHUNK_1_A1 = 256 : i64}}], intent_gpu.triton.legalized} {
    %0 = "intent_gpu.parameter"() <{parameter = #intent_gpu.parameter<"NUM_WARPS", 4, 6, 0, [8, 4, 16]>}> : () -> index
    %1 = "intent_gpu.parameter"() <{parameter = #intent_gpu.parameter<"NUM_STAGES", 5, 6, 0, [2]>}> : () -> index
    %2 = "intent_gpu.parameter"() <{parameter = #intent_gpu.parameter<"NUM_CTAS", 6, 6, 0, [1]>}> : () -> index
    %3 = "intent_gpu.parameter"() <{parameter = #intent_gpu.parameter<"REDUCE_CHUNK_1_A1", 13, 1, 32, [8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192]>}> {intent_gpu.dimension = 1 : i64} : () -> index
    %4 = "intent_gpu.parameter"() <{parameter = #intent_gpu.parameter<"REDUCE_CHUNK_1_A0", 12, 1, 32, [8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096]>}> {intent_gpu.dimension = 1 : i64} : () -> index
    %cst = arith.constant {intent_gpu.origin = 1 : i64} 0.000000e+00 : f32
    %c1 = arith.constant 1 : index
    %5 = "intent_gpu.program_id"() <{axis = 0 : i64}> : () -> index
    %6 = "intent_gpu.delinearize"(%5, %c1) <{launch_extents = [#intent_gpu.expr<0, 1, "", []>]}> {intent_gpu.execution_group = 0 : i64, intent_gpu.segment_length = #intent_gpu.expr<0, 1, "", []>, intent_gpu.segment_offset = #intent_gpu.expr<0, 0, "", []>} : (index, index) -> index
    %c0 = arith.constant 0 : index
    %c1_0 = arith.constant 1 : index
    %c0_1 = arith.constant 0 : index
    %c1_2 = arith.constant 1 : index
    %7 = "intent_gpu.dim"(%arg0) <{axis = 0 : i64}> : (!intent_gpu.view<f32, 2, 0, 0, 1, <[#intent_gpu.expr<2, 1, "D1", []>, #intent_gpu.expr<2, 1, "D1", []>], [1, 1], true, ["S0_0", "S0_1"], "", false>>) -> index
    %8 = "intent_gpu.dim"(%arg0) <{axis = 1 : i64}> : (!intent_gpu.view<f32, 2, 0, 0, 1, <[#intent_gpu.expr<2, 1, "D1", []>, #intent_gpu.expr<2, 1, "D1", []>], [1, 1], true, ["S0_0", "S0_1"], "", false>>) -> index
    %cst_3 = arith.constant 0.000000e+00 : f32
    %9 = scf.for %arg5 = %c0 to %arg2 step %4 iter_args(%arg6 = %cst) -> (f32) {
      %10 = "intent_gpu.make_range"(%arg5, %4, %c1_0, %c0, %arg2) <{derived = false, source_axis = 0 : i64, source_id = 1 : i64}> : (index, index, index, index, index) -> !intent_gpu.fragment<index, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>], 1, 1>
      %11 = "intent_gpu.splat"(%7) : (index) -> !intent_gpu.fragment<index, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>], 1, 1>
      %12 = "intent_gpu.compare"(%10, %11) <{predicate = #intent.compare_predicate<lt>}> : (!intent_gpu.fragment<index, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>], 1, 1>, !intent_gpu.fragment<index, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>], 1, 1>) -> !intent_gpu.fragment<i1, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>], 1, 1>
      %13 = "intent_gpu.make_range"(%arg5, %4, %c1_0, %c0, %arg2) <{derived = false, source_axis = 0 : i64, source_id = 1 : i64}> : (index, index, index, index, index) -> !intent_gpu.fragment<index, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>], 1, 1>
      %14 = "intent_gpu.broadcast"(%arg2) : (index) -> !intent_gpu.fragment<index, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>], 1, 1>
      %15 = "intent_gpu.compare"(%13, %14) <{predicate = #intent.compare_predicate<lt>}> : (!intent_gpu.fragment<index, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>], 1, 1>, !intent_gpu.fragment<index, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>], 1, 1>) -> !intent_gpu.fragment<i1, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>], 1, 1>
      %16 = "intent_gpu.splat"(%cst) : (f32) -> !intent_gpu.fragment<f32, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>], 1, 1>
      %17 = scf.for %arg7 = %c0_1 to %arg2 step %3 iter_args(%arg8 = %16) -> (!intent_gpu.fragment<f32, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>], 1, 1>) {
        %20 = "intent_gpu.make_range"(%arg7, %3, %c1_2, %c0_1, %arg2) <{derived = false, source_axis = 1 : i64, source_id = 1 : i64}> : (index, index, index, index, index) -> !intent_gpu.fragment<index, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 1, 1, 0, false>], 1, 1>
        %21 = "intent_gpu.broadcast"(%arg2) : (index) -> !intent_gpu.fragment<index, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 1, 1, 0, false>], 1, 1>
        %22 = "intent_gpu.compare"(%20, %21) <{predicate = #intent.compare_predicate<lt>}> : (!intent_gpu.fragment<index, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 1, 1, 0, false>], 1, 1>, !intent_gpu.fragment<index, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 1, 1, 0, false>], 1, 1>) -> !intent_gpu.fragment<i1, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 1, 1, 0, false>], 1, 1>
        %23 = "intent_gpu.broadcast"(%22) : (!intent_gpu.fragment<i1, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 1, 1, 0, false>], 1, 1>) -> !intent_gpu.fragment<i1, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>, #intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>, #intent_gpu.axis_map<1, 1, 1, 1, false>], 1, 1>
        %24 = "intent_gpu.make_range"(%arg7, %3, %c1_2, %c0_1, %arg2) <{derived = false, source_axis = 1 : i64, source_id = 1 : i64}> : (index, index, index, index, index) -> !intent_gpu.fragment<index, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 1, 1, 0, false>], 1, 1>
        %25 = "intent_gpu.compare"(%24, %21) <{predicate = #intent.compare_predicate<lt>}> : (!intent_gpu.fragment<index, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 1, 1, 0, false>], 1, 1>, !intent_gpu.fragment<index, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 1, 1, 0, false>], 1, 1>) -> !intent_gpu.fragment<i1, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 1, 1, 0, false>], 1, 1>
        %26 = "intent_gpu.broadcast"(%25) : (!intent_gpu.fragment<i1, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 1, 1, 0, false>], 1, 1>) -> !intent_gpu.fragment<i1, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>, #intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>, #intent_gpu.axis_map<1, 1, 1, 1, false>], 1, 1>
        %27 = "intent_gpu.splat"(%8) : (index) -> !intent_gpu.fragment<index, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 1, 1, 0, false>], 1, 1>
        %28 = "intent_gpu.compare"(%20, %27) <{predicate = #intent.compare_predicate<lt>}> : (!intent_gpu.fragment<index, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 1, 1, 0, false>], 1, 1>, !intent_gpu.fragment<index, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 1, 1, 0, false>], 1, 1>) -> !intent_gpu.fragment<i1, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 1, 1, 0, false>], 1, 1>
        %29 = "intent_gpu.broadcast"(%28) : (!intent_gpu.fragment<i1, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 1, 1, 0, false>], 1, 1>) -> !intent_gpu.fragment<i1, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>, #intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>, #intent_gpu.axis_map<1, 1, 1, 1, false>], 1, 1>
        %30 = "intent_gpu.broadcast"(%12) : (!intent_gpu.fragment<i1, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>], 1, 1>) -> !intent_gpu.fragment<i1, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>, #intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>, #intent_gpu.axis_map<1, 1, 1, 1, false>], 1, 1>
        %31 = "intent_gpu.binary"(%30, %29) <{approximate = false, flush_to_zero = false, operator_kind = #intent.binary_operator<logical_and>}> : (!intent_gpu.fragment<i1, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>, #intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>, #intent_gpu.axis_map<1, 1, 1, 1, false>], 1, 1>, !intent_gpu.fragment<i1, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>, #intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>, #intent_gpu.axis_map<1, 1, 1, 1, false>], 1, 1>) -> !intent_gpu.fragment<i1, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>, #intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>, #intent_gpu.axis_map<1, 1, 1, 1, false>], 1, 1>
        %32 = "intent_gpu.binary"(%26, %31) <{approximate = false, flush_to_zero = false, operator_kind = #intent.binary_operator<logical_and>}> : (!intent_gpu.fragment<i1, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>, #intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>, #intent_gpu.axis_map<1, 1, 1, 1, false>], 1, 1>, !intent_gpu.fragment<i1, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>, #intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>, #intent_gpu.axis_map<1, 1, 1, 1, false>], 1, 1>) -> !intent_gpu.fragment<i1, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>, #intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>, #intent_gpu.axis_map<1, 1, 1, 1, false>], 1, 1>
        %33 = "intent_gpu.splat"(%cst_3) : (f32) -> !intent_gpu.fragment<f32, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>, #intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>, #intent_gpu.axis_map<1, 1, 1, 1, false>], 1, 1>
        %34 = "intent_gpu.splat"(%cst) : (f32) -> !intent_gpu.fragment<f32, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>, #intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>, #intent_gpu.axis_map<1, 1, 1, 1, false>], 1, 1>
        %35 = "intent_gpu.broadcast"(%15) : (!intent_gpu.fragment<i1, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>], 1, 1>) -> !intent_gpu.fragment<i1, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>, #intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>, #intent_gpu.axis_map<1, 1, 1, 1, false>], 1, 1>
        %36 = "intent_gpu.broadcast"(%16) : (!intent_gpu.fragment<f32, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>], 1, 1>) -> !intent_gpu.fragment<f32, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>, #intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>, #intent_gpu.axis_map<1, 1, 1, 1, false>], 1, 1>
        %37 = "intent_triton.block_load"(%arg0, %arg5, %arg7) <{block_axes = array<i64: 0, 1>, boundary_axes = array<i64: 0, 1>, order = array<i64: 1, 0>, padding = "zero"}> : (!intent_gpu.view<f32, 2, 0, 0, 1, <[#intent_gpu.expr<2, 1, "D1", []>, #intent_gpu.expr<2, 1, "D1", []>], [1, 1], true, ["S0_0", "S0_1"], "", false>>, index, index) -> !intent_gpu.fragment<f32, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>, #intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>, #intent_gpu.axis_map<1, 1, 1, 1, false>], 1, 1>
        %38 = "intent_gpu.select"(%35, %37, %34) : (!intent_gpu.fragment<i1, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>, #intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>, #intent_gpu.axis_map<1, 1, 1, 1, false>], 1, 1>, !intent_gpu.fragment<f32, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>, #intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>, #intent_gpu.axis_map<1, 1, 1, 1, false>], 1, 1>, !intent_gpu.fragment<f32, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>, #intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>, #intent_gpu.axis_map<1, 1, 1, 1, false>], 1, 1>) -> !intent_gpu.fragment<f32, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>, #intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>, #intent_gpu.axis_map<1, 1, 1, 1, false>], 1, 1>
        %39 = "intent_gpu.select"(%23, %38, %36) : (!intent_gpu.fragment<i1, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>, #intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>, #intent_gpu.axis_map<1, 1, 1, 1, false>], 1, 1>, !intent_gpu.fragment<f32, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>, #intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>, #intent_gpu.axis_map<1, 1, 1, 1, false>], 1, 1>, !intent_gpu.fragment<f32, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>, #intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>, #intent_gpu.axis_map<1, 1, 1, 1, false>], 1, 1>) -> !intent_gpu.fragment<f32, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>, #intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>, #intent_gpu.axis_map<1, 1, 1, 1, false>], 1, 1>
        %40 = "intent_gpu.reduce"(%39, %16) <{axes = array<i64: 1>, capture_count = 0 : i64, identity_count = 1 : i64, source_count = 1 : i64}> ({
        ^bb0(%arg9: !intent_gpu.fragment<f32, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>], 1, 1>, %arg10: !intent_gpu.fragment<f32, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>], 1, 1>):
          %42 = "intent_gpu.binary"(%arg9, %arg10) <{approximate = false, flush_to_zero = false, operator_kind = #intent.binary_operator<add>}> {intent_gpu.origin = 2 : i64} : (!intent_gpu.fragment<f32, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>], 1, 1>, !intent_gpu.fragment<f32, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>], 1, 1>) -> !intent_gpu.fragment<f32, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>], 1, 1>
          "intent_gpu.yield"(%42) : (!intent_gpu.fragment<f32, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>], 1, 1>) -> ()
        }) {intent_gpu.origin = 4 : i64, intent_gpu.triton.reduce_form = "sum"} : (!intent_gpu.fragment<f32, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>, #intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A1", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>, #intent_gpu.axis_map<1, 1, 1, 1, false>], 1, 1>, !intent_gpu.fragment<f32, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>], 1, 1>) -> !intent_gpu.fragment<f32, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>], 1, 1>
        %41 = "intent_gpu.binary"(%arg8, %40) <{approximate = false, flush_to_zero = false, operator_kind = #intent.binary_operator<add>}> {intent_gpu.origin = 2 : i64} : (!intent_gpu.fragment<f32, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>], 1, 1>, !intent_gpu.fragment<f32, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>], 1, 1>) -> !intent_gpu.fragment<f32, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>], 1, 1>
        scf.yield %41 : !intent_gpu.fragment<f32, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>], 1, 1>
      } {intent_gpu.origin = 4 : i64, intent_gpu.reduction_sources = [#intent_gpu.source<1, 1, false>]}
      %18 = "intent_gpu.reduce"(%17, %cst) <{axes = array<i64: 0>, capture_count = 0 : i64, identity_count = 1 : i64, source_count = 1 : i64}> ({
      ^bb0(%arg7: f32, %arg8: f32):
        %20 = "intent_gpu.binary"(%arg7, %arg8) <{approximate = false, flush_to_zero = false, operator_kind = #intent.binary_operator<add>}> {intent_gpu.origin = 2 : i64} : (f32, f32) -> f32
        "intent_gpu.yield"(%20) : (f32) -> ()
      }) {intent_gpu.origin = 4 : i64, intent_gpu.triton.reduce_form = "sum"} : (!intent_gpu.fragment<f32, [#intent_gpu.expr<1, 0, "REDUCE_CHUNK_1_A0", []>], [#intent_gpu.axis_map<1, 0, 1, 0, false>], 1, 1>, f32) -> f32
      %19 = "intent_gpu.binary"(%arg6, %18) <{approximate = false, flush_to_zero = false, operator_kind = #intent.binary_operator<add>}> {intent_gpu.origin = 2 : i64} : (f32, f32) -> f32
      scf.yield %19 : f32
    } {intent_gpu.origin = 4 : i64, intent_gpu.reduction_sources = [#intent_gpu.source<1, 0, false>, #intent_gpu.source<1, 1, false>]}
    "intent_gpu.store"(%arg1, %9) <{operandSegmentSizes = array<i32: 1, 0, 1, 0>, source_axes = array<i64>}> {intent_gpu.origin = 5 : i64} : (!intent_gpu.view<f32, 0, 1, 1, 2, <[], [], true, [], "", false>>, f32) -> ()
    return
  }
}
